/*
 * Copyright 2026 Maximilian Schwärzler
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */

package com.anzhuo.todo.ui.theme
import androidx.compose.ui.graphics.Color

val primaryLight = Color(0xFF3F5F90)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFD6E3FF)
val onPrimaryContainerLight = Color(0xFF254777)
val secondaryLight = Color(0xFF00696B)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFF9CF1F2)
val onSecondaryContainerLight = Color(0xFF004F50)
val tertiaryLight = Color(0xFF666014)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFEEE58C)
val onTertiaryContainerLight = Color(0xFF4D4800)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF93000A)
val backgroundLight = Color(0xFFF9F9FF)
val onBackgroundLight = Color(0xFF191C20)
val surfaceLight = Color(0xFFF9F9FF)
val onSurfaceLight = Color(0xFF191C20)
val surfaceVariantLight = Color(0xFFE0E2EC)
val onSurfaceVariantLight = Color(0xFF43474E)
val outlineLight = Color(0xFF74777F)
val outlineVariantLight = Color(0xFFC4C6CF)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF2E3035)
val inverseOnSurfaceLight = Color(0xFFF0F0F7)
val inversePrimaryLight = Color(0xFFA8C8FF)
val surfaceDimLight = Color(0xFFD9D9E0)
val surfaceBrightLight = Color(0xFFF9F9FF)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFF3F3FA)
val surfaceContainerLight = Color(0xFFEDEDF4)
val surfaceContainerHighLight = Color(0xFFE7E8EE)
val surfaceContainerHighestLight = Color(0xFFE2E2E9)

//val primaryLightMediumContrast = Color(0xFF103665)
//val onPrimaryLightMediumContrast = Color(0xFFFFFFFF)
//val primaryContainerLightMediumContrast = Color(0xFF4E6EA0)
//val onPrimaryContainerLightMediumContrast = Color(0xFFFFFFFF)
//val secondaryLightMediumContrast = Color(0xFF003D3E)
//val onSecondaryLightMediumContrast = Color(0xFFFFFFFF)
//val secondaryContainerLightMediumContrast = Color(0xFF16797A)
//val onSecondaryContainerLightMediumContrast = Color(0xFFFFFFFF)
//val tertiaryLightMediumContrast = Color(0xFF3B3700)
//val onTertiaryLightMediumContrast = Color(0xFFFFFFFF)
//val tertiaryContainerLightMediumContrast = Color(0xFF756F23)
//val onTertiaryContainerLightMediumContrast = Color(0xFFFFFFFF)
//val errorLightMediumContrast = Color(0xFF740006)
//val onErrorLightMediumContrast = Color(0xFFFFFFFF)
//val errorContainerLightMediumContrast = Color(0xFFCF2C27)
//val onErrorContainerLightMediumContrast = Color(0xFFFFFFFF)
//val backgroundLightMediumContrast = Color(0xFFF9F9FF)
//val onBackgroundLightMediumContrast = Color(0xFF191C20)
//val surfaceLightMediumContrast = Color(0xFFF9F9FF)
//val onSurfaceLightMediumContrast = Color(0xFF0F1116)
//val surfaceVariantLightMediumContrast = Color(0xFFE0E2EC)
//val onSurfaceVariantLightMediumContrast = Color(0xFF33363E)
//val outlineLightMediumContrast = Color(0xFF4F525A)
//val outlineVariantLightMediumContrast = Color(0xFF6A6D75)
//val scrimLightMediumContrast = Color(0xFF000000)
//val inverseSurfaceLightMediumContrast = Color(0xFF2E3035)
//val inverseOnSurfaceLightMediumContrast = Color(0xFFF0F0F7)
//val inversePrimaryLightMediumContrast = Color(0xFFA8C8FF)
//val surfaceDimLightMediumContrast = Color(0xFFC5C6CD)
//val surfaceBrightLightMediumContrast = Color(0xFFF9F9FF)
//val surfaceContainerLowestLightMediumContrast = Color(0xFFFFFFFF)
//val surfaceContainerLowLightMediumContrast = Color(0xFFF3F3FA)
//val surfaceContainerLightMediumContrast = Color(0xFFE7E8EE)
//val surfaceContainerHighLightMediumContrast = Color(0xFFDCDCE3)
//val surfaceContainerHighestLightMediumContrast = Color(0xFFD0D1D8)
//
//val primaryLightHighContrast = Color(0xFF002C5A)
//val onPrimaryLightHighContrast = Color(0xFFFFFFFF)
//val primaryContainerLightHighContrast = Color(0xFF284979)
//val onPrimaryContainerLightHighContrast = Color(0xFFFFFFFF)
//val secondaryLightHighContrast = Color(0xFF003233)
//val onSecondaryLightHighContrast = Color(0xFFFFFFFF)
//val secondaryContainerLightHighContrast = Color(0xFF005253)
//val onSecondaryContainerLightHighContrast = Color(0xFFFFFFFF)
//val tertiaryLightHighContrast = Color(0xFF302D00)
//val onTertiaryLightHighContrast = Color(0xFFFFFFFF)
//val tertiaryContainerLightHighContrast = Color(0xFF504B00)
//val onTertiaryContainerLightHighContrast = Color(0xFFFFFFFF)
//val errorLightHighContrast = Color(0xFF600004)
//val onErrorLightHighContrast = Color(0xFFFFFFFF)
//val errorContainerLightHighContrast = Color(0xFF98000A)
//val onErrorContainerLightHighContrast = Color(0xFFFFFFFF)
//val backgroundLightHighContrast = Color(0xFFF9F9FF)
//val onBackgroundLightHighContrast = Color(0xFF191C20)
//val surfaceLightHighContrast = Color(0xFFF9F9FF)
//val onSurfaceLightHighContrast = Color(0xFF000000)
//val surfaceVariantLightHighContrast = Color(0xFFE0E2EC)
//val onSurfaceVariantLightHighContrast = Color(0xFF000000)
//val outlineLightHighContrast = Color(0xFF292C33)
//val outlineVariantLightHighContrast = Color(0xFF464951)
//val scrimLightHighContrast = Color(0xFF000000)
//val inverseSurfaceLightHighContrast = Color(0xFF2E3035)
//val inverseOnSurfaceLightHighContrast = Color(0xFFFFFFFF)
//val inversePrimaryLightHighContrast = Color(0xFFA8C8FF)
//val surfaceDimLightHighContrast = Color(0xFFB7B8BF)
//val surfaceBrightLightHighContrast = Color(0xFFF9F9FF)
//val surfaceContainerLowestLightHighContrast = Color(0xFFFFFFFF)
//val surfaceContainerLowLightHighContrast = Color(0xFFF0F0F7)
//val surfaceContainerLightHighContrast = Color(0xFFE2E2E9)
//val surfaceContainerHighLightHighContrast = Color(0xFFD3D4DB)
//val surfaceContainerHighestLightHighContrast = Color(0xFFC5C6CD)

val primaryDark = Color(0xFFA8C8FF)
val onPrimaryDark = Color(0xFF06305F)
val primaryContainerDark = Color(0xFF254777)
val onPrimaryContainerDark = Color(0xFFD6E3FF)
val secondaryDark = Color(0xFF80D4D5)
val onSecondaryDark = Color(0xFF003737)
val secondaryContainerDark = Color(0xFF004F50)
val onSecondaryContainerDark = Color(0xFF9CF1F2)
val tertiaryDark = Color(0xFFD1C973)
val onTertiaryDark = Color(0xFF353100)
val tertiaryContainerDark = Color(0xFF4D4800)
val onTertiaryContainerDark = Color(0xFFEEE58C)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF111318)
val onBackgroundDark = Color(0xFFE2E2E9)
val surfaceDark = Color(0xFF111318)
val onSurfaceDark = Color(0xFFE2E2E9)
val surfaceVariantDark = Color(0xFF43474E)
val onSurfaceVariantDark = Color(0xFFC4C6CF)
val outlineDark = Color(0xFF8E9099)
val outlineVariantDark = Color(0xFF43474E)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFE2E2E9)
val inverseOnSurfaceDark = Color(0xFF2E3035)
val inversePrimaryDark = Color(0xFF3F5F90)
val surfaceDimDark = Color(0xFF111318)
val surfaceBrightDark = Color(0xFF37393E)
val surfaceContainerLowestDark = Color(0xFF0C0E13)
val surfaceContainerLowDark = Color(0xFF191C20)
val surfaceContainerDark = Color(0xFF1D2024)
val surfaceContainerHighDark = Color(0xFF282A2F)
val surfaceContainerHighestDark = Color(0xFF33353A)

//val primaryDarkMediumContrast = Color(0xFFCCDDFF)
//val onPrimaryDarkMediumContrast = Color(0xFF00254E)
//val primaryContainerDarkMediumContrast = Color(0xFF7292C6)
//val onPrimaryContainerDarkMediumContrast = Color(0xFF000000)
//val secondaryDarkMediumContrast = Color(0xFF96EBEB)
//val onSecondaryDarkMediumContrast = Color(0xFF002B2B)
//val secondaryContainerDarkMediumContrast = Color(0xFF479E9F)
//val onSecondaryContainerDarkMediumContrast = Color(0xFF000000)
//val tertiaryDarkMediumContrast = Color(0xFFE7DF86)
//val onTertiaryDarkMediumContrast = Color(0xFF292600)
//val tertiaryContainerDarkMediumContrast = Color(0xFF9A9343)
//val onTertiaryContainerDarkMediumContrast = Color(0xFF000000)
//val errorDarkMediumContrast = Color(0xFFFFD2CC)
//val onErrorDarkMediumContrast = Color(0xFF540003)
//val errorContainerDarkMediumContrast = Color(0xFFFF5449)
//val onErrorContainerDarkMediumContrast = Color(0xFF000000)
//val backgroundDarkMediumContrast = Color(0xFF111318)
//val onBackgroundDarkMediumContrast = Color(0xFFE2E2E9)
//val surfaceDarkMediumContrast = Color(0xFF111318)
//val onSurfaceDarkMediumContrast = Color(0xFFFFFFFF)
//val surfaceVariantDarkMediumContrast = Color(0xFF43474E)
//val onSurfaceVariantDarkMediumContrast = Color(0xFFDADCE5)
//val outlineDarkMediumContrast = Color(0xFFAFB2BB)
//val outlineVariantDarkMediumContrast = Color(0xFF8D9099)
//val scrimDarkMediumContrast = Color(0xFF000000)
//val inverseSurfaceDarkMediumContrast = Color(0xFFE2E2E9)
//val inverseOnSurfaceDarkMediumContrast = Color(0xFF282A2F)
//val inversePrimaryDarkMediumContrast = Color(0xFF274878)
//val surfaceDimDarkMediumContrast = Color(0xFF111318)
//val surfaceBrightDarkMediumContrast = Color(0xFF42444A)
//val surfaceContainerLowestDarkMediumContrast = Color(0xFF06070C)
//val surfaceContainerLowDarkMediumContrast = Color(0xFF1B1E22)
//val surfaceContainerDarkMediumContrast = Color(0xFF26282D)
//val surfaceContainerHighDarkMediumContrast = Color(0xFF303338)
//val surfaceContainerHighestDarkMediumContrast = Color(0xFF3C3E43)
//
//val primaryDarkHighContrast = Color(0xFFEBF0FF)
//val onPrimaryDarkHighContrast = Color(0xFF000000)
//val primaryContainerDarkHighContrast = Color(0xFFA4C4FB)
//val onPrimaryContainerDarkHighContrast = Color(0xFF000B1F)
//val secondaryDarkHighContrast = Color(0xFFACFEFF)
//val onSecondaryDarkHighContrast = Color(0xFF000000)
//val secondaryContainerDarkHighContrast = Color(0xFF7CD0D1)
//val onSecondaryContainerDarkHighContrast = Color(0xFF000E0E)
//val tertiaryDarkHighContrast = Color(0xFFFCF398)
//val onTertiaryDarkHighContrast = Color(0xFF000000)
//val tertiaryContainerDarkHighContrast = Color(0xFFCDC56F)
//val onTertiaryContainerDarkHighContrast = Color(0xFF0D0C00)
//val errorDarkHighContrast = Color(0xFFFFECE9)
//val onErrorDarkHighContrast = Color(0xFF000000)
//val errorContainerDarkHighContrast = Color(0xFFFFAEA4)
//val onErrorContainerDarkHighContrast = Color(0xFF220001)
//val backgroundDarkHighContrast = Color(0xFF111318)
//val onBackgroundDarkHighContrast = Color(0xFFE2E2E9)
//val surfaceDarkHighContrast = Color(0xFF111318)
//val onSurfaceDarkHighContrast = Color(0xFFFFFFFF)
//val surfaceVariantDarkHighContrast = Color(0xFF43474E)
//val onSurfaceVariantDarkHighContrast = Color(0xFFFFFFFF)
//val outlineDarkHighContrast = Color(0xFFEEF0F9)
//val outlineVariantDarkHighContrast = Color(0xFFC0C2CC)
//val scrimDarkHighContrast = Color(0xFF000000)
//val inverseSurfaceDarkHighContrast = Color(0xFFE2E2E9)
//val inverseOnSurfaceDarkHighContrast = Color(0xFF000000)
//val inversePrimaryDarkHighContrast = Color(0xFF274878)
//val surfaceDimDarkHighContrast = Color(0xFF111318)
//val surfaceBrightDarkHighContrast = Color(0xFF4E5055)
//val surfaceContainerLowestDarkHighContrast = Color(0xFF000000)
//val surfaceContainerLowDarkHighContrast = Color(0xFF1D2024)
//val surfaceContainerDarkHighContrast = Color(0xFF2E3035)
//val surfaceContainerHighDarkHighContrast = Color(0xFF393B41)
//val surfaceContainerHighestDarkHighContrast = Color(0xFF45474C)







